FROM node:18.12.0-alpine

WORKDIR /app

RUN npm install

ARG NODE_ENV
ARG ENCRYPTION_PASS_PHRASE
ARG ENCRYPTION_PRIVATE_KEY

ENV NODE_ENV=$NODE_ENV
ENV ENCRYPTION_PASS_PHRASE=$ENCRYPTION_PASS_PHRASE
ENV ENCRYPTION_PRIVATE_KEY=$ENCRYPTION_PRIVATE_KEY

RUN node -r esm scripts/decrypt.js

CMD ["npm", "start"]